name: ci
permissions: {}
on:
  push:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true
jobs:
  dev: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      
      - name: Create two large files
        run: |
          yes "Hello World" | head -c 1368709120 > 1GB_text_file.txt
          yes "Hello Worldsss" | head -c 1368709120 > 1GB_text_file2.txt

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run tests
        run: bun test
